export enum PermissionsList{

    LISTAR_ROLES = 100,
    CREAR_ROLES = 101,
    ACTUALIZAR_ROLES = 102,
    ELIMINAR_ROLES = 103,
    CONSULTAR_ROLES = 104,
    LISTAR_PERMISOS = 105,
    LISTAR_VOLUNTARIOS = 200,
    CREAR_VOLUNTARIOS = 201,
    ACTUALIZAR_VOLUNTARIOS = 202,
    CONSULTAR_VOLUNTARIO = 203,
    CONSULTAR_VOLUNTARIO_POSICION = 204,
    LISTAR_EMPRESAS = 300,
    CREAR_EMPRESAS = 301,
    ACTUALIZAR_EMPRESAS = 302,
    CONSULTAR_NIT = 303,
    CONSULTAR_EMPRESA_DOCUMENTO = 304

}